#!/bin/sh

# Ensure persistent installation of ZeroTier for UniFi OS >2.0 devices

# User Modifiable Variables (DATA_DIR should be within /data/___ to persist)
DEBUG=1				        # shows output to terminal if TRUE
UTIL_DIR='/data/unifios-utils'
DATA_DIR="$UTIL_DIR/.config"         	# Set persistent folder location

# Non-User Modifiable Variables (strongly recommend not modifying)
ZT_DIR=/var/lib/zerotier-one	        # Location for ZeroTier config

# Check is ZeroTier has previously been installed
if [ -d $DATA_DIR/zerotier-one ]; then
  if [ $DEBUG -eq 1 ]; then
    echo "$DATA_DIR/zerotier-one exists, assuming it has valid ZT files"
  fi
else
  if [ $DEBUG -eq 1 ]; then
    echo "$DATA_DIR/zerotier-one does not exist, so this is initial install"
    echo "Installing ZeroTier from https://install.zerotier.com"
  fi
  curl -s https://install.zerotier.com | sudo bash
  while [ ! -f /var/lib/zerotier-one/identity.secret ]; do
        sleep 1
  done
  systemctl stop zerotier-one
  mv $ZT_DIR "$DATA_DIR/"
  ln -s "$DATA_DIR/zerotier-one" $ZT_DIR
  systemctl start zerotier-one
  if [ $DEBUG -eq 1 ]; then
    echo 'This is an initial install of ZeroTier, once complete'
    echo 'a network can be joined by executing the command:'
    echo 'zerotier-cli join <NETWORK_ID>'
    echo 'see doc/zerotier-one.md for more details'
  fi
fi

# Check if the ZT package is installed, if not then install it
if [ $(dpkg-query -W -f='${Status}' zerotier-one 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
  if [ $DEBUG -eq 1 ]; then
    echo "zerotier-one is not installed"
  fi
  rm -rf $ZT_DIR
  apt install zerotier-one
  wait $!
  if [ $DEBUG -eq 1 ]; then
    echo "ZeroTier package has been installed, ensuring persistence..."
  fi
  systemctl stop zerotier-one
  rm -rf $ZT_DIR
  ln -s "$DATA_DIR/zerotier-one" $ZT_DIR
  systemctl start zerotier-one
  if [ $DEBUG -eq 1 ]; then
    echo "ZeroTier has been installed and is persistent"
  fi
else
  if [ $DEBUG -eq 1 ]; then
    echo "zerotier-one is already installed"
  fi
fi

exit 0
